import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '../components/global/header'
import Footer from '../components/global/footer'
import {roboto} from '@/app/lib/fonts'


export const metadata: Metadata = {
  title: 'Constance RDC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex flex-col`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer /> 
      </body>
    </html>
  )
}
